server:
  port: 8021
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      server-addr: 192.168.137.137:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
#        ephemeral: false #默认true临时实例，false为永久实例，即无用的实例也存在nacos服务列表中