server:
  port: 8031
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.137.137:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
#直接在配置文件设置不使用ribbon
    loadbalancer:
      ribbon:
        enabled: false